### ISSUE TITLE
New button (only for clients) to refer to an issue

### ISSUE THREAD

**Issue by lvca** [orientechnologies/prjhub#76]
The issue will be managed separately, with own SLA, but in the description there will be the link to the original one automatically.

**Comment by jillray7** [comment]
@maggiolo00 To better explain this issue, sometimes issues are reported by a user in github or by other clients that are important to many clients. For now, when a github issue is also important to a client, they have to create an issue in Project Hub and refer to the github issue. We want to make this an easier process, so that a Project Hub issue is automatically created when a github issue is referred to. This way, the OT Team is aware of the issue's importance to the client. Also, the client is able to have an SLA on the issue.
